//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horoscope
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nikhil_Username
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> dob { get; set; }
        public Nullable<int> mob { get; set; }
        public Nullable<int> yob { get; set; }
    }
}
