//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horoscope
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nikhil_Horoscope
    {
        public int MyDate { get; set; }
        public string aries { get; set; }
        public string taurus { get; set; }
        public string gemini { get; set; }
        public string cancer { get; set; }
        public string leo { get; set; }
        public string virgo { get; set; }
        public string libra { get; set; }
        public string scorpio { get; set; }
        public string saggitarius { get; set; }
        public string capricorn { get; set; }
        public string aquarius { get; set; }
        public string pisces { get; set; }
    }
}
